### ISSUE TITLE
Give a method to deny permissions

### ISSUE THREAD

**Issue by rocboronat** [SchibstedSpain/Barista#112]
Thanks to @crgarridos and his PR #110 , now we know the ID of the button to reject a permission in a permission dialog. We could write another method to give the tester the option to deny a permission.

**Comment by Sloy** [comment]
I would usually discourage against trying to deny a permission from a test, because you can't be sure that the permission is not accepted already, because you can't revoke them between tests.

On the other hand, if the new experimental Test Orchestrator works fine, it will allow to start each test without any permissions. So... 

Good idea!

**Comment by rocboronat** [comment]
@Sloy what do you think about doing it after migrating to Espresso 3?

**Comment by Sloy** [comment]
Sure I think Espresso 3 is top priority right now, if it really fixes a lot of flakiness as they say. I didn't open an issue but I'm already on it.

**Comment by rocboronat** [comment]
Too old + never needed + 0 👍= close.
Feel free to reopen it if needed.
