### ISSUE TITLE
Waiting for get response synchronously

### ISSUE THREAD

**Issue by MortezaAghili** [SchibstedSpain/Barista#138]
Hey guys, 

Did you implemented way to waiting for getting some data from the API or anywhere else? in espresso we have **Espresso idling resource** mechanism  to seamlessly synchronize all test but that difficult to implement. 

Thanks,
Morteza.

**Comment by Sloy** [comment]
Hi @MortezaAghili! 
We don't include any new way to wait for asynchronous operation. Currently we use Espresso's Idling resources, as you say. I don't think there's much that can be done about it from our side.

There are multiple idling resources out there implemented for different use cases, like RxJava, OkHttp, etc. We also create our own based on the framework's [CountingIdlingResource](https://developer.android.com/reference/android/support/test/espresso/idling/CountingIdlingResource.html), which is easier to use than the bare `IdlingResource` interface.

**Comment by MortezaAghili** [comment]
Thanks for your response @Sloy!

I thought you've implemented a way like **[ConditionWatcher](https://github.com/AzimoLabs/ConditionWatcher)** (by @AzimoLabs). It is a great library that I've used and i thought a combination of these two libraries will be great.

Thanks.

**Comment by Sloy** [comment]
Interesting @MortezaAghili, I didn't know about that library.
To be honest, after reading the article about it I'm not really convinced. We didn't have the problems with IdlingResources described by the guys from @AzimoLabs. We use them in a different way though, we un/register global IdlingResources from a JUnit Rule and our tests don't know anything else about them.

Actually with the CountingIdlingResource and some third-party libraries built around it we've pretty much covered all of our cases. Maybe we should write a blog post showing our approach.

Anyways, you can still use ConditionWatcher with Barista the same way you would with Espresso. I just don't think we will add any specific features related to it or anything similar.

Thank you for opening the issue, I would not have known about ConditionWatcher otherwise. 😄 
Let me close the issue, you are always welcome to open as many as you want.
