### ISSUE TITLE
Typo at "SomeViewsWithDifferentVisibilitesActivity"

### ISSUE THREAD

**Issue by rocboronat** [SchibstedSpain/Barista#153]
"SomeViewsWithDifferentVisibilitesActivity" != "SomeViewsWithDifferentVisibilitiesActivity"

I avoid doing a PR because I know @Sloy is doing a massive refactor 👁‍🗨 👁

**Comment by EsteveAguilera** [comment]
This issue has been fixed on #149 and merged into **barista2**

To avoid future issues already fixed on **barista2** and PRs pointing to **master**, maybe it will be a good idea to talk about the new version you're working on (the README can be a good place), so people can focus on **barista2** branch instead of **master**

**Comment by EsteveAguilera** [comment]
@Sloy @rocboronat I think you can close this Issue...
