### ISSUE TITLE
Add option to set different locales for tests?

### ISSUE THREAD

**Issue by EsteveAguilera** [SchibstedSpain/Barista#248]
I am currently working on a project with different languages. As you know, the texts on the different languages can be really different when talking about length.

I think it can be helpful to have an option to set a different locale for a given test. 

I am not sure if this is a feature that will fit the Barista essence, so before doing any step I prefer to ask...

**Comment by rocboronat** [comment]
I get it but I can't figure why a Locale could make a test fail. Do you have any example of it? I mean, do you have any test that needs to be executed in a given Locale in order to pass?

**Comment by Sloy** [comment]
Did you ever make it @EsteveAguilera?

I know there are [some implementations](https://github.com/fastlane/fastlane/blob/master/screengrab/screengrab-lib/src/main/java/tools.fastlane.screengrab/locale/LocaleUtil.java) out there, but they work differently between android releases and can break easily. 

I would not like to maintain such thing 😂 But that is because I never needed this feature

**Comment by Sloy** [comment]
¯\\\_(ツ)\_/¯
