### ISSUE TITLE
Program type already present: androidx.test.InstrumentationRegistry

### ISSUE THREAD

**Issue by serandel** [SchibstedSpain/Barista#281]
Hi, I'm trying to add Barista to a brand new project, but I'm having this error.

This is my dependencies block: 

```
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'androidx.appcompat:appcompat:1.0.2'
    implementation 'androidx.core:core-ktx:1.0.1'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.0'
    androidTestImplementation('com.schibsted.spain:barista:2.7.1') {
        exclude group: 'com.android.support'
        exclude group: 'org.jetbrains.kotlin' // Only if you already use Kotlin in your project
    }
}
```

I haven't coded anything in AndroidX before, but it seems like it could be a bug in Jetifier again, as in #268? I've tried to exclude the module with the InstrumentationRegistry class, both in Android Support and in AndroidX, with no success...

```
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'androidx.appcompat:appcompat:1.0.2'
    implementation 'androidx.core:core-ktx:1.0.1'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.0'
    androidTestImplementation('com.schibsted.spain:barista:2.7.1') {
        exclude group: 'com.android.support'
        exclude group: 'org.jetbrains.kotlin' // Only if you already use Kotlin in your project
        exclude group: 'com.android.support.test', module: 'runner'
        exclude group: 'androidx.test', module: 'monitor'
    }
}
```

**Comment by serandel** [comment]
compile and target are 28 both, BTW

**Comment by Sloy** [comment]
Hi @serandel! Thanks for the report. 
I can't seem to be able to reproduce your issue :( 
Is your project open source by any chance? Otherwise, could you set up a sample reproducing it so we can help you?

The only thing I can think of is to add `exclude group: 'com.android.support.test.espresso'` and see if that works ¯\\\_(ツ)\_/¯

**Comment by serandel** [comment]
Hi @Sloy. That exclude didn't work (and I can't understand why my other two didn't neither.) Project is not open source but right now is barely a minimum scaffolding, so I've added you as a collaborator. I'm trying to do `gradle assembleDebugAndroidTest` from the branch `task/3/espresso`.

If you prefer, I could copy that into another repo or extract the sample, whatever is easier for you. :)

Thanks!!!

**Comment by Sloy** [comment]
Ok I can reproduce your issue with your project. But I can't see why it fails in yours but not in mine. I will investigate a bit and see if I can figure it out 👍

**Comment by serandel** [comment]
Please, tell me if I can help in any way! :)

**Comment by serandel** [comment]
Also checked with Barista 2.8.0

**Comment by Sloy** [comment]
No way, I don't see it. I reduced your config to the minimum with Barista as the only dependency, and it still fails. 

```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 28
    defaultConfig {
        applicationId "org.granchi.learningsubs"
        minSdkVersion 16
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
    }
}

dependencies {
    androidTestImplementation('com.schibsted.spain:barista:2.7.1')
}
```

I also tried adding Barista to a shiny new project, and it also fails. With and without excludes. 
It seems like it's an issue with Jetifier, but I'm not sure what is actually going on. Also I don't know why it seems to be working in my own project. Try opening an issue in Google's bug tracker, they might know better.

Sorry I can be of more help :( 
We'll give a second thought to migrating to AndroidX.

**Comment by serandel** [comment]
I also tried updating Jetifier to this week's release, with no success

```
buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build.jetifier:jetifier-processor:1.0.0-beta04'
    }
}
```

I'm opening a bug in Google's bug tracker, and I'm keen on forking Barista and try to migrate it to AndroidX, if it's of any help.

**Comment by serandel** [comment]
https://issuetracker.google.com/issues/126604279

**Comment by AllanHasegawa** [comment]
Solved by excluding the AndroidX version of Espresso:

```
    androidTestImplementation('com.schibsted.spain:barista:2.8.0') {
        exclude group: 'androidx.test.espresso'
        exclude group: 'org.jetbrains.kotlin' // Only if you already use Kotlin in your project
    }
```

I then had to manually depend on Espresso:

```
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0-alpha02'
    androidTestImplementation 'androidx.test.espresso:espresso-contrib:3.2.0-alpha02'
```

**Comment by serandel** [comment]
Tested, that did the trick. :)

Thanks, @AllanHasegawa !!!

**Comment by Zeeshan0201** [comment]
@AllanHasegawa  Getting same error like this..
Program type already present: androidx.work.ArrayCreatingInputMerger...
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithMultidexlistForDebug'.
> com.android.build.api.transform.TransformException: Error while generating the main dex list:
  Error while merging dex archives: 
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
  Program type already present: androidx.work.ArrayCreatingInputMerger

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Gradle task assembleDebug failed with exit code 1

can you please help me?

**Comment by Ankit-Jangid** [comment]
that worked for me either, but in this method : 
"Context appContext = **InstrumentationRegistry**.getTargetContext();
InstrumentationRegistry shows deprecated . Which is imported from using:
 import androidx.test.InstrumentationRegistry;

Any idea how to solve the deprecated problem so it doesn't create problem in future at least for some time .

![image](https://user-images.githubusercontent.com/14173520/69477568-9c6d6480-0e0d-11ea-8a30-c66c071d95fd.png)

However it is working still but not sure how long will it be. thanks
