### ISSUE TITLE
BaristaRule re-runs failing tests even if they're not defined as flaky

### ISSUE THREAD

**Issue by lovelylauz219** [SchibstedSpain/Barista#284]
When creating UI test classes written in Kotlin and using`BaristaRule`. I am finding that failing tests are automatically re-run, up to 10 times. From reading the documentation, I assumed that this would only happen if a test is deemed as flaky, however, the failing tests have not been labelled with `@AllowFlaky` or `@Repeat(times = 5)`. Not sure if this expected behaviour or could be an issue?

Furthermore, when I launch multiple activities in a test class, with more than 1 activity, my test will re-run more than 10 times (10 per activity found in the class). I currently launch 3 activities at different points within my tests and so a failing test is re-run up to 30 times. 

Any advice/guidance on the above would be greatly appreciated 👍

**Comment by rocboronat** [comment]
Hello @lovelylauz219! Yes, it's the expected behavior. We explain it at https://github.com/SchibstedSpain/Barista#one-rule-to-rule-them-all, or at least we try to. If you think that we could explain it better, don't hesitate to open a PR :·)

By the way, right now, the best way to avoid this repetition is to annotate your method with `@Repeat (times = 1)`. By the way, feel free to +1 the issue #137.

Feel free to close the issue if you think that this answer solves it 😄

**Comment by lovelylauz219** [comment]
Hey - thanks for the response. Yes, this does solve my dilemma, ended up making a custom set of rules. Will close and +1 issue #137. Thank you 👍

**Comment by rocboronat** [comment]
My pleasure! 😄
