### ISSUE TITLE
Feature request: add a way to read a textview from a recyclerview

### ISSUE THREAD

**Issue by kenyee** [SchibstedSpain/Barista#296]
Use case is testing master/detail views (e.g., you have a recyclerview and you want to see if clicking on an item gets you the right item in a new activity that shows up w/ the details screen for the item).

You can click on the item now using:
clickListItem(R.id.list, 4)

Before that, it'd be useful to be able to do:
getListItemViewText(R.id.list, 4, R.id.myTextView)

which will read the value of the text view item so it can be compared when the espresso test runs the clickListItem() and then it can be used for an assert.

**Comment by Sloy** [comment]
Hi @kenyee. I think the implementation for that would be a bit too complex for the use case. 
Instead I would suggest you setup your test data to be what you expect. If you know your 4th item in the list will be an Avocado and you click it, you can verify that the detail shown is for the Avocado too.

**Comment by kenyee** [comment]
Already tried convincing the higher ups that we should use mock data, but they want E2E tests...these tests hit a live server :-(

**Comment by Sloy** [comment]
In that case you're going to have a bad time writing tests. In general 🙄

Anyways, I don't think Barista can help you with this. It's intended to work with Espresso mechanisms, not skip them.

You could try accessing the view hierarchy via `activityRule.getActivity().findViewById(R.id...)` or something like that, but I'm not sure how that will work. Beware that the test runs in a different thread, not the Android's main thread. 

I'm closing the issue since Barista is not intended for the use case, sorry.
