### ISSUE TITLE
PermissionGranter doesn't work on Android 23 or 25

### ISSUE THREAD

**Issue by rocboronat** [SchibstedSpain/Barista#61]
Reproduced with QuitNow! tests on the emulator. PermissionGranter just avoids tapping the accept button.

**Comment by rocboronat** [comment]
We should install all emulators and try from 19 to 25.

**Comment by Sloy** [comment]
23 and 25? Or 23 to 25?

**Comment by Sloy** [comment]
There is no test in Barista for PermissionGranter. That could be helpful.

**Comment by rocboronat** [comment]
Don't know. Right now, I just tested with 23 and 25. +1 to those tests! 👨‍❤️‍👨

**Comment by Sloy** [comment]
I was going to write them last night, but some guys texted me to play PS4 online so... I didn't. Shame.

**Comment by rocboronat** [comment]
Hahahahaha *THAT KIND OF GUYS*

**Comment by Sloy** [comment]
Ha! Got it! It looks like we use an old custom PermissionGranter at InfoJobs, that's why it works there.
The problem is with `BaristaSleepActions.sleep(3000L);`. The sleep action requires an Activity to be resumed, and when the permission dialog is shown there isn't any. So Espresso waits until the timeout and fails because it can't sleep. Life's funny.

If we replace the sleep action with a good old Thread.sleep it should work again.

**Comment by rocboronat** [comment]
Wow! Move on please!

Roc Boronat
http://fewlaps.com

2017-06-19 8:22 GMT+02:00 Rafa Vázquez <notifications@github.com>:
